import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import os
import requests
from fpdf import FPDF

# --- 1. AI 营养分析逻辑 ---
def get_ai_advice(food_name, protein, fat, region):
    api_url = "https://api.deepseek.com/chat/completions"
    try:
        # 获取 Secrets 中的 Key
        api_key = st.secrets["DEEPSEEK_API_KEY"]
    except:
        return "请在 Streamlit Secrets 中配置 API Key 🔑"
    
    prompt = f"""
    你是一位精通中国饮食文化的营养专家。
    食物：{food_name}（蛋白质：{protein}g，脂肪：{fat}g）。
    地域习惯：{region}。
    请提供：1.该食物的中国名产地；2.针对{region}人群的建议；3.一句话点评。
    要求：中文回答，150字以内。
    """
    
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    data = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.7
    }
    try:
        response = requests.post(api_url, json=data, headers=headers, timeout=15)
        return response.json()['choices'][0]['message']['content']
    except:
        return "AI 正在思考中，请稍后刷新页面..."

# --- 2. 稳定版 PDF 生成函数 (避免字符报错) ---
def create_pdf_report(name, p, f, region):
    pdf = FPDF()
    pdf.add_page()
    
    # 顶部装饰条：薄荷绿
    pdf.set_fill_color(46, 204, 113) 
    pdf.rect(0, 0, 210, 40, 'F')
    
    # 标题 (英文，避免 Unicode 报错)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("helvetica", 'B', 24)
    pdf.cell(0, 20, "Nutrition Analysis Report", ln=True, align='C')
    pdf.ln(10)
    
    # 内容主体
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("helvetica", 'B', 14)
    pdf.cell(0, 10, f"Food Analysis: {name}", ln=True)
    pdf.set_draw_color(46, 204, 113)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # 数据展示
    pdf.set_font("helvetica", size=12)
    pdf.cell(0, 10, f"User Region Preset: {region}", ln=True)
    pdf.cell(50, 10, f"Protein: {p}g")
    pdf.cell(50, 10, f"Fat: {f}g", ln=True)
    pdf.ln(10)
    
    # 提示信息
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("helvetica", 'B', 12)
    pdf.cell(0, 10, " AI Coach Notice:", ln=True, fill=True)
    pdf.set_font("helvetica", size=10)
    notice = (
        "The customized Chinese analysis has been generated on your dashboard. "
        "Due to PDF encoding standards, please view the full regional advice "
        "and sourcing details on the live application page."
    )
    pdf.multi_cell(0, 8, txt=notice)
    
    pdf.set_y(-20)
    pdf.set_font("helvetica", 'I', 8)
    pdf.cell(0, 10, "Generated by AI Nutrition Lab", align='C')
    
    return pdf.output()

# --- 3. Streamlit 页面主程序 ---
st.set_page_config(page_title="AI 营养实验室", layout="wide")
st.title("🥗 AI 智能营养实验室")

# 侧边栏地域选择
st.sidebar.header("🌍 地域偏好")
region_option = st.sidebar.selectbox(
    "您的饮食背景：",
    ["Sichuan/Chongqing (Spicy)", "North China (Salty)", "Guangdong (Light)", "Jiangsu/Zhejiang (Sweet)"]
)

csv_file = 'protein_vs_fat.csv'
if os.path.exists(csv_file):
    df = pd.read_csv(csv_file)
    query = st.text_input("🔍 搜索食物名称 (如 Beef):", "Chicken")
    
    res = df[df['Food_Name'].str.contains(query, case=False)]
    
    if not res.empty:
        food = res.iloc[0]
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.subheader("📊 营养指标与 AI 建议")
            # 修复显示重复的 Bug
            c1, c2 = st.columns(2)
            c1.metric("蛋白质 (Protein)", f"{food['Protein_Value']}g")
            c2.metric("脂肪 (Fat)", f"{food['Fat_Value']}g")
            
            with st.spinner('正在调取地域营养数据库...'):
                advice = get_ai_advice(food['Food_Name'], food['Protein_Value'], food['Fat_Value'], region_option)
            
            st.info(f"**AI 营养师建议：**\n\n{advice}")
            
            # PDF 下载
            try:
                # 传入英文名以防报错
                report_pdf = create_pdf_report(food['Food_Name'], food['Protein_Value'], food['Fat_Value'], region_option)
                st.download_button(
                    label="📥 下载专业营养报告 (PDF)",
                    data=bytes(report_pdf),
                    file_name=f"Report_{food['Food_Name']}.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"PDF 导出失败: {e}")

        with col2:
            st.subheader("🔥 能量供能比")
            fig, ax = plt.subplots(figsize=(6, 6))
            p_energy = food['Protein_Value'] * 4
            f_energy = food['Fat_Value'] * 9
            ax.pie([p_energy, f_energy], labels=['Protein', 'Fat'], autopct='%1.1f%%', colors=['#2ecc71', '#e67e22'], startangle=140)
            st.pyplot(fig)
    else:
        st.warning("未找到匹配食物。")
else:
    st.error("数据文件丢失。")
