import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import os
import requests
from fpdf import FPDF  # 注意：在 requirements.txt 中安装 fpdf2 后，导入依然是 from fpdf

# --- 1. AI 营养分析逻辑 ---
def get_ai_advice(food_name, protein, fat, region):
    api_url = "https://api.deepseek.com/chat/completions"
    try:
        # 从 Streamlit Secrets 安全读取 Key
        api_key = st.secrets["DEEPSEEK_API_KEY"]
    except:
        return "请在 Streamlit Secrets 中配置 API Key 🔑"
    
    # 根据地域习惯定制 Prompt
    prompt = f"""
    你是一位精通中国饮食文化的营养专家。
    食物：{food_name}（蛋白质：{protein}g，脂肪：{fat}g）。
    用户所在地域习惯：{region}。
    请提供：
    1. 【地域产地】：该食物在中国最出名的产地。
    2. 【饮食建议】：针对{region}人群的建议。
    3. 【专业点评】：一句话总结。
    注意：请用简洁的中文回答，不超过150字。
    """
    
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    data = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.7
    }
    try:
        response = requests.post(api_url, json=data, headers=headers, timeout=15)
        return response.json()['choices'][0]['message']['content']
    except:
        return "AI 营养师正在查看地图，请稍后再试..."

# --- 2. 增强版 PDF 生成函数 (100% 解决中文报错) ---
def create_pdf_report(name, p, f, advice, region):
    # 初始化 PDF 实例
    pdf = FPDF()
    pdf.add_page()
    
    # 顶部装饰：薄荷绿背景
    pdf.set_fill_color(46, 204, 113) 
    pdf.rect(0, 0, 210, 40, 'F')
    
    # 报告标题 (纯英文防止编码报错)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("helvetica", 'B', 24)
    pdf.cell(0, 20, "Nutrition Analysis Report", ln=True, align='C')
    pdf.ln(10)
    
    # 回到主体内容文字
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("helvetica", 'B', 14)
    pdf.cell(0, 10, f"Analysis for: {name}", ln=True)
    pdf.set_draw_color(46, 204, 113)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # 营养数据展示
    pdf.set_font("helvetica", size=12)
    pdf.cell(0, 10, f"Region Setting: {region}", ln=True)
    pdf.cell(50, 10, f"Protein: {p}g")
    pdf.cell(50, 10, f"Fat: {f}g", ln=True)
    pdf.ln(10)
    
    # AI 建议板块
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("helvetica", 'B', 13)
    pdf.cell(0, 10, " AI Coach Advice:", ln=True, fill=True)
    pdf.ln(2)
    pdf.set_font("helvetica", size=11)
    
    # 处理中文报错的关键：PDF 内部只显示英文说明
    # 这样可以保证生成的 PDF 永远不会崩溃
    summary_text = (
        "The AI has successfully generated a customized nutrition plan. "
        "Due to PDF encoding constraints, please refer to the website's "
        "live dashboard for the full Chinese analysis and regional advice."
    )
    pdf.multi_cell(0, 8, txt=summary_text)
    
    # 页脚
    pdf.set_y(-20)
    pdf.set_font("helvetica", 'I', 8)
    pdf.cell(0, 10, "Generated by AI Nutrition Lab - Personalized Health Assistant", align='C')
    
    # fpdf2 中直接调用 output() 会返回字节流
    return pdf.output()

# --- 3. Streamlit 界面显示 ---
st.set_page_config(page_title="AI 营养实验室", layout="wide")
st.title("🥗 AI 智能营养实验室")

# 侧边栏
st.sidebar.header("🌍 偏好设置")
selected_region = st.sidebar.selectbox(
    "选择您的饮食习惯地域：",
    ["川渝地区 (Spicy)", "北方地区 (Salty/Carb)", "广东地区 (Light/Herbal)", "江浙沪 (Sweet/Fresh)", "西北地区 (Meat/Noodle)"]
)

# 读取 CSV 数据
csv_file = 'protein_vs_fat.csv'
if os.path.exists(csv_file):
    df = pd.read_csv(csv_file)
    search_query = st.text_input("🔍 搜索食物名称 (如 Chicken):", "Chicken")
    
    # 模糊匹配
    res = df[df['Food_Name'].str.contains(search_query, case=False)]
    
    if not res.empty:
        food = res.iloc[0]
        
        # 布局
        c1, c2 = st.columns([1, 1])
        with c1:
            st.subheader("📊 营养指标与建议")
            # 清爽的指标显示
            m1, m2 = st.columns(2)
            m1.metric("蛋白质 (Protein)", f"{food['Protein_Value']}g")
            m2.metric("脂肪 (Fat)", f"{food['Fat_Value']}g")
            
            # AI 分析过程
            with st.spinner('AI 正在结合地域特色深度分析中...'):
                ai_advice = get_ai_advice(food['Food_Name'], food['Protein_Value'], food['Fat_Value'], selected_region)
            
            st.info(f"**AI 针对【{selected_region}】的专业分析：**\n\n{ai_advice}")
            
            # PDF 按钮
            try:
                pdf_content = create_pdf_report(food['Food_Name'], food['Protein_Value'], food['Fat_Value'], ai_advice, selected_region)
                st.download_button(
                    label="📥 下载精美营养报告 (PDF)",
                    data=bytes(pdf_content),
                    file_name=f"Analysis_{food['Food_Name']}.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"PDF 生成遇到一点小麻烦: {e}")

        with c2:
            st.subheader("🔥 能量比例图")
            fig, ax = plt.subplots(figsize=(6, 6))
            p_energy = food['Protein_Value'] * 4
            f_energy = food['Fat_Value'] * 9
            ax.pie([p_energy, f_energy], labels=['Protein', 'Fat'], autopct='%1.1f%%', colors=['#2ecc71', '#e67e22'], startangle=90)
            st.pyplot(fig)
    else:
        st.warning("没找到该食物，尝试搜索其他名称吧。")
else:
    st.error("未发现 protein_vs_fat.csv，请确保文件已上传到项目根目录。")
