import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import os
import requests
from fpdf import FPDF

# --- 1. AI 营养分析逻辑 ---
def get_ai_advice(food_name, protein, fat, region):
    api_url = "https://api.deepseek.com/chat/completions"
    try:
        api_key = st.secrets["DEEPSEEK_API_KEY"]
    except:
        return "请在 Streamlit Secrets 中配置 API Key 🔑"
    
    prompt = f"""
    你是一位精通中国饮食文化的营养专家。
    当前食物：{food_name}（蛋白质：{protein}g，脂肪：{fat}g）。
    用户所在地域：{region}。
    请提供：
    1. 【地域溯源】：该食物在中国的主要产地或地标。
    2. 【人群习惯】：针对{region}人群的健康建议。
    3. 【营养评价】：一句话总结。
    注意：请用简洁的中文回答，不要超过150字。
    """
    
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    data = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.7
    }
    try:
        response = requests.post(api_url, json=data, headers=headers, timeout=15)
        return response.json()['choices'][0]['message']['content']
    except:
        return "AI 营养师正在查看地方志，请稍后再试..."

# --- 2. 增强版 PDF 报告生成 (更美观) ---
def create_pdf_report(name, p, f, advice, region):
    pdf = FPDF()
    pdf.add_page()
    
    # 页眉：薄荷绿背景
    pdf.set_fill_color(46, 204, 113) 
    pdf.rect(0, 0, 210, 40, 'F')
    
    # 标题
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 24)
    pdf.cell(0, 20, "Nutrition Analysis Report", ln=True, align='C')
    pdf.ln(10)
    
    # 主体内容
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, f"Target Food: {name}", ln=True)
    pdf.set_draw_color(46, 204, 113)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y()) # 绿色分割线
    pdf.ln(5)
    
    # 数据展示
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Region Context: {region}", ln=True)
    pdf.cell(50, 10, f"Protein: {p}g")
    pdf.cell(50, 10, f"Fat: {f}g", ln=True)
    pdf.ln(5)
    
    # AI 建议板块
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 10, " AI Coach Advice (Summary):", ln=True, fill=True)
    pdf.ln(2)
    pdf.set_font("Arial", size=11)
    
    # 处理中文乱码：目前 FPDF 默认不支持中文，PDF 内部建议先显示英文摘要
    # 如果 AI 返回中文，PDF 打印时会略过非 Latin 字符，我们提示用户看网页详细版
    clean_advice = advice.encode('latin-1', 'ignore').decode('latin-1')
    if not clean_advice.strip():
        clean_advice = "The full Chinese report is available on the website. [AI Analysis Completed]"
        
    pdf.multi_cell(0, 8, txt=clean_advice)
    
    # 页脚
    pdf.set_y(-20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by Gemini-Powered AI Nutrition Lab", align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- 3. Streamlit 页面布局 ---
st.set_page_config(page_title="AI 营养实验室", layout="wide")
st.title("🥗 AI 智能营养实验室")

# 侧边栏
st.sidebar.header("🌍 地域设定")
user_region = st.sidebar.selectbox(
    "您的饮食习惯习惯：",
    ["川渝地区 (Heavy Spice)", "北方地区 (High Salt/Carb)", "广东地区 (Light/Herbal)", "江浙沪 (Sweet/Fresh)", "西北地区 (Meat/Noodle)"]
)

# 加载数据
csv_path = 'protein_vs_fat.csv'
if os.path.exists(csv_path):
    df = pd.read_csv(csv_path)
    search_term = st.text_input("🔍 搜索食物名称 (英文):", "Chicken")
    
    filtered_df = df[df['Food_Name'].str.contains(search_term, case=False)]
    
    if not filtered_df.empty:
        top_food = filtered_df.iloc[0]
        
        # 左右布局
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.subheader("📊 营养数据与 AI 建议")
            
            # 优化后的指标显示，不再重复
            m1, m2 = st.columns(2)
            m1.metric("蛋白质 (Protein)", f"{top_food['Protein_Value']}g")
            m2.metric("脂肪 (Fat)", f"{top_food['Fat_Value']}g")
            
            # AI 分析
            with st.spinner('AI 正在结合地域习惯分析中...'):
                advice = get_ai_advice(top_food['Food_Name'], top_food['Protein_Value'], top_food['Fat_Value'], user_region)
            
            st.info(f"**AI 建议 ({user_region}):**\n\n{advice}")
            
            # 漂亮报告下载按钮
            pdf_bytes = create_pdf_report(top_food['Food_Name'], top_food['Protein_Value'], top_food['Fat_Value'], advice, user_region)
            st.download_button(
                label="📥 下载精美营养报告 (PDF)",
                data=pdf_bytes,
                file_name=f"Nutrition_Report_{top_food['Food_Name']}.pdf",
                mime="application/pdf"
            )

        with col2:
            st.subheader("🔥 能量配比图")
            fig, ax = plt.subplots(figsize=(6, 6))
            # 计算热量比例
            p_cal = top_food['Protein_Value'] * 4
            f_cal = top_food['Fat_Value'] * 9
            ax.pie([p_cal, f_cal], labels=['Protein', 'Fat'], autopct='%1.1f%%', colors=['#2ecc71', '#e67e22'], startangle=140)
            st.pyplot(fig)
    else:
        st.warning("未找到匹配食物，请换个词试试。")
else:
    st.error("找不到数据库文件 protein_vs_fat.csv，请检查路径。")

